# Generated by Django 4.1.3 on 2022-12-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_controller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='id',
        ),
        migrations.AlterField(
            model_name='controller',
            name='attribute',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
