# Generated by Django 4.1.3 on 2022-12-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_controller_id_alter_controller_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
